/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parroquia_cristo_resucitado;

import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author luis9
 */
public class RecuperacionUser extends javax.swing.JFrame {

    
    /**
     * Creates new form RecuperacionUser
     */
    public RecuperacionUser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnenviar = new javax.swing.JButton();
        btnmin = new javax.swing.JLabel();
        btnexit = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(720, 403));
        setMinimumSize(new java.awt.Dimension(720, 403));
        setUndecorated(true);
        setSize(new java.awt.Dimension(720, 403));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Candara", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 23, 18));
        jLabel1.setText("RESTABLECIMIENTO DE CONTRASEÑA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 35, -1, -1));

        jLabel2.setFont(new java.awt.Font("Candara", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 23, 18));
        jLabel2.setText("Ingrese su Corre Electrónico:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 199, -1, -1));

        txtemail.setBorder(null);
        txtemail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 270, 37));

        btnenviar.setBackground(new java.awt.Color(255, 255, 255));
        btnenviar.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        btnenviar.setForeground(new java.awt.Color(240, 23, 18));
        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnenviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 180, 50));

        btnmin.setBackground(new java.awt.Color(240, 23, 18));
        btnmin.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnmin.setForeground(new java.awt.Color(240, 23, 18));
        btnmin.setText("-");
        btnmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminMouseClicked(evt);
            }
        });
        jPanel1.add(btnmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 30, -1));

        btnexit.setBackground(new java.awt.Color(240, 23, 18));
        btnexit.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 18)); // NOI18N
        btnexit.setForeground(new java.awt.Color(240, 23, 18));
        btnexit.setText("X");
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnexitMouseClicked(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 30, -1));

        jSeparator2.setBackground(new java.awt.Color(240, 23, 18));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 280, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void btnminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_btnminMouseClicked

    private void btnexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnexitMouseClicked
        
      dispose();
     Login opp = new Login();
     opp.show();
        
    }//GEN-LAST:event_btnexitMouseClicked

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed
        // TODO add your handling code here:
            basededatos bd=new basededatos();
            Statement stmt=null;
            ResultSet rs=null;
            bd.conexion();
            char valor='0';
            String pass="0";

            try
            {

                CallableStatement call=bd.con.prepareCall("{CALL busqueda_email(?)}");
                call.setString(1, txtemail.getText());
                call.execute();
                rs = call.getResultSet();
                while(rs.next())
                {
                   valor=rs.getString(1).charAt(0);
                   pass=rs.getString(1);
                }
            }
            catch(Exception ex)
            {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
            
            if(valor=='&')
            {
                JOptionPane.showMessageDialog(this, "Este correo no está vinculado con ningún usuario.");
            }
            else
            {
                Email gm=new  Email();
                gm.enviarcorreo("remitente@gmail.com", "password", txtemail.getText(), pass, "Recuperación de contraseña");
                JOptionPane.showMessageDialog(this, "Éxito, se ha enviado un correo con tu contraseña."); 
            }
    }//GEN-LAST:event_btnenviarActionPerformed

class Email 
{

        public boolean enviarcorreo(String de, String clave,String para,String mensaje,String asunto)
        {
        boolean enviado = false;
        try{

                    String host="smtp.gmail.com";

                    Properties prop=System.getProperties();

                    prop.put("mail.smtp.starttls.enable","true");
                    prop.put("mail.smtp.host",host);
                    prop.put("mail.smtp.user",de);
                    prop.put("mail.smtp.password",clave);
                    prop.put("mail.smtp.port",587);
                    prop.put("mail.smtp.auth", "true");

                    Session session=Session.getDefaultInstance(prop,null);
                    MimeMessage message= new MimeMessage(session);

                    message.setFrom(new InternetAddress(de));

                    message.setRecipient(Message.RecipientType.TO, new InternetAddress(para));
                    message.setSubject(asunto);
                    message.setText(mensaje);

                    System.out.print(message);

                    Transport transport=session.getTransport("smtp");
                    transport.connect(host,de,clave);

                    transport.sendMessage(message, message.getAllRecipients());
                    transport.close();
                    enviado=true;
                    System.out.print(enviado);

            }
            catch (Exception e)
            {
                    e.printStackTrace();

            }
                return enviado;

        }

}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperacionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperacionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperacionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperacionUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperacionUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JLabel btnexit;
    private javax.swing.JLabel btnmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables
}
